# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.6
  - nightly

dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:jonathonf/texlive-2016
  - sudo apt-get -qq update
  - sudo apt-get install -y gnuplot
  - sudo apt-get install -y pdf2svg
  - sudo apt-get install -y texlive
  - sudo apt-get install -y texlive-latex-extra
notifications:
  email: false
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("PGFPlotsX"); Pkg.test("PGFPlotsX"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("PGFPlotsX")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
